[project]
name = "SS_SWE_Ergometer"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Mani5623", email = "hm9703@mci4me.at"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
